version: '3'
services:
  ecommerce-server:
    build: 
      context: .
      target: production
      args:
        NODE_ENV: production   
    ports: # No need for port when we use nginx
      - $PORT:$PORT  
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://gofasthorse.com:3000
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://gofasthorse.com:3000/api/auth/google/callback
      - FRONT_END_REDIRECT=http://gofasthorse.com:3000/login
      - FRONT_END_CART_URL=http://gofasthorse.com:3000/main/personal/cart
      - FRONT_END_CHECKOUT_SUCCESS_URL=http://gofasthorse.com:3000/main/personal/success
    command: ./wait-for-it/wait-for-it.sh mysqldb:$DATABASE_PORT --strict --timeout=300 -- node dist/index.js
 
         